"""initial schema — create all Governance Store tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-19

The POC keeps the schema defined in the SQLAlchemy models as the single source
of truth. This migration materialises the entire model metadata in one step so
that `alembic upgrade head` and the app's startup create_all stay consistent.
Subsequent schema changes should be expressed as ordinary autogenerated
revisions on top of this baseline.
"""
from __future__ import annotations

from alembic import op

from src.database import Base
from src import models  # noqa: F401 — registers tables on Base.metadata

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
