/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_agents__agent_id__get"];
        put?: never;
        post?: never;
        /**
         * Retire Agent
         * @description Soft delete: set status=retired (FR-GS-2).
         */
        delete: operations["retire_agent_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_agents__agent_id__patch"];
        trace?: never;
    };
    "/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evals */
        get: operations["list_evals_evals_get"];
        put?: never;
        /** Create Eval */
        post: operations["create_eval_evals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{eval_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval */
        get: operations["get_eval_evals__eval_pk__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Eval */
        patch: operations["update_eval_evals__eval_pk__patch"];
        trace?: never;
    };
    "/evals/{eval_pk}/submit-for-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit For Review */
        post: operations["submit_for_review_evals__eval_pk__submit_for_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{eval_pk}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_evals__eval_pk__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{eval_pk}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deprecate */
        post: operations["deprecate_evals__eval_pk__deprecate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{eval_pk}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach Calibration
         * @description Attach a calibration set and run the agreement test.
         *
         *     The POC simulates a judge-vs-human agreement run by averaging the per-example
         *     agreement scores in the calibration set. The result is stored on the eval as
         *     `last_judge_human_agreement`, gating approval (FR-GS-3).
         */
        post: operations["attach_calibration_evals__eval_pk__calibration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval-agent-mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mappings */
        get: operations["list_mappings_eval_agent_mapping_get"];
        put?: never;
        /** Create Mapping */
        post: operations["create_mapping_eval_agent_mapping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibration-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calibration Sets */
        get: operations["list_calibration_sets_calibration_sets_get"];
        put?: never;
        /** Create Calibration Set */
        post: operations["create_calibration_set_calibration_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibration-sets/{cal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calibration Set */
        get: operations["get_calibration_set_calibration_sets__cal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/change-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Change Events */
        get: operations["query_change_events_change_events_get"];
        put?: never;
        /** Ingest Change Event */
        post: operations["ingest_change_event_change_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Eval Results */
        get: operations["query_eval_results_eval_results_get"];
        put?: never;
        /** Create Eval Result */
        post: operations["create_eval_result_eval_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval-results/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate Eval Results
         * @description Aggregate scores per (agent, eval). pass_rate uses PASS_VERDICTS.
         */
        get: operations["aggregate_eval_results_eval_results_aggregate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regression-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_regression_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_regression_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regression-alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_regression_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Alert */
        patch: operations["update_alert_regression_alerts__alert_id__patch"];
        trace?: never;
    };
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query Audit Log
         * @description Read the append-only audit trail (NFR-8). No write/update/delete here.
         */
        get: operations["query_audit_log_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorBody */
        ActorBody: {
            /**
             * Actor
             * @default ui
             */
            actor: string;
        };
        /** AgentCreate */
        AgentCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Framework
             * @default custom
             */
            framework: string;
            /**
             * Owner Team
             * @default unassigned
             */
            owner_team: string;
            /**
             * Owner Email
             * @default
             */
            owner_email: string;
            /** @default low */
            criticality: components["schemas"]["Criticality"];
            /** @default internal */
            data_classification: components["schemas"]["DataClassification"];
            /**
             * Business Unit
             * @default unassigned
             */
            business_unit: string;
            /**
             * Is Third Party
             * @default false
             */
            is_third_party: boolean;
        };
        /** AgentOut */
        AgentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Framework */
            framework: string;
            /** Owner Team */
            owner_team: string;
            /** Owner Email */
            owner_email: string;
            /** Criticality */
            criticality: string;
            /** Data Classification */
            data_classification: string;
            /** Business Unit */
            business_unit: string;
            /** Is Third Party */
            is_third_party: boolean;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AgentStatus
         * @enum {string}
         */
        AgentStatus: "active" | "deprecated" | "retired";
        /** AgentUpdate */
        AgentUpdate: {
            /** Description */
            description?: string | null;
            /** Framework */
            framework?: string | null;
            /** Owner Team */
            owner_team?: string | null;
            /** Owner Email */
            owner_email?: string | null;
            criticality?: components["schemas"]["Criticality"] | null;
            data_classification?: components["schemas"]["DataClassification"] | null;
            /** Business Unit */
            business_unit?: string | null;
            /** Is Third Party */
            is_third_party?: boolean | null;
            status?: components["schemas"]["AgentStatus"] | null;
        };
        /** ApproveBody */
        ApproveBody: {
            /**
             * Approver Email
             * Format: email
             */
            approver_email: string;
            /**
             * Actor
             * @default ui
             */
            actor: string;
        };
        /** AttachCalibrationBody */
        AttachCalibrationBody: {
            /**
             * Calibration Set Id
             * Format: uuid
             */
            calibration_set_id: string;
            /**
             * Actor
             * @default ui
             */
            actor: string;
        };
        /** AuditLogOut */
        AuditLogOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string;
            /** Detail */
            detail: Record<string, never>;
        };
        /** CalibrationExample */
        CalibrationExample: {
            /** Input */
            input: string;
            /** Output */
            output: string;
            /** Human Verdict */
            human_verdict: string;
            /**
             * Rater Count
             * @default 1
             */
            rater_count: number;
            /**
             * Agreement
             * @default 1
             */
            agreement: number;
        };
        /** CalibrationSetCreate */
        CalibrationSetCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Examples */
            examples?: components["schemas"]["CalibrationExample"][];
        };
        /** CalibrationSetOut */
        CalibrationSetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Examples */
            examples: Record<string, never>[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChangeEventCreate */
        ChangeEventCreate: {
            /** Event Type */
            event_type: string;
            /** Timestamp */
            timestamp?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Actor
             * @default system
             */
            actor: string;
            /** Before */
            before?: Record<string, never>;
            /** After */
            after?: Record<string, never>;
            /** Reason */
            reason?: string | null;
        };
        /** ChangeEventOut */
        ChangeEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Event Type */
            event_type: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string | null;
            /** Actor */
            actor: string;
            /** Before */
            before: Record<string, never>;
            /** After */
            after: Record<string, never>;
            /** Reason */
            reason: string | null;
        };
        /**
         * Criticality
         * @enum {string}
         */
        Criticality: "low" | "medium" | "high" | "critical";
        /**
         * DataClassification
         * @enum {string}
         */
        DataClassification: "public" | "internal" | "confidential" | "restricted";
        /** EvalAgentMappingCreate */
        EvalAgentMappingCreate: {
            /**
             * Eval Id
             * Format: uuid
             */
            eval_id: string;
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Sample Rate
             * @default 1
             */
            sample_rate: number;
        };
        /** EvalAgentMappingOut */
        EvalAgentMappingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Eval Id
             * Format: uuid
             */
            eval_id: string;
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Enabled */
            enabled: boolean;
            /** Sample Rate */
            sample_rate: number;
        };
        /** EvalCreate */
        EvalCreate: {
            /** Eval Id */
            eval_id: string;
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
            /**
             * Criterion Description
             * @default
             */
            criterion_description: string;
            /** @default llm_as_judge */
            evaluator_type: components["schemas"]["EvaluatorType"];
            /** Judge Config */
            judge_config?: Record<string, never>;
            /** Prompt Template */
            prompt_template?: string | null;
            /** Output Schema */
            output_schema?: Record<string, never>;
            /** Retrieval Config */
            retrieval_config?: Record<string, never> | null;
            /**
             * Agreement Threshold
             * @default 0.75
             */
            agreement_threshold: number;
            /** Execution Modes */
            execution_modes?: Record<string, never>;
            /**
             * Owner Team
             * @default unassigned
             */
            owner_team: string;
            /**
             * Owner Email
             * @default
             */
            owner_email: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /** EvalOut */
        EvalOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Eval Id */
            eval_id: string;
            /** Version */
            version: string;
            /** Criterion Description */
            criterion_description: string;
            /** Evaluator Type */
            evaluator_type: string;
            /** Judge Config */
            judge_config: Record<string, never>;
            /** Prompt Template */
            prompt_template: string | null;
            /** Output Schema */
            output_schema: Record<string, never>;
            /** Retrieval Config */
            retrieval_config: Record<string, never> | null;
            /** Calibration Set Id */
            calibration_set_id: string | null;
            /** Last Judge Human Agreement */
            last_judge_human_agreement: number | null;
            /** Agreement Threshold */
            agreement_threshold: number;
            /** Execution Modes */
            execution_modes: Record<string, never>;
            /** Owner Team */
            owner_team: string;
            /** Owner Email */
            owner_email: string;
            /** Approver Email */
            approver_email: string | null;
            /** Review Status */
            review_status: string;
            /** Approved At */
            approved_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EvalResultAggregate */
        EvalResultAggregate: {
            /** Agent Id */
            agent_id: string | null;
            /** Eval Id */
            eval_id: string;
            /** Count */
            count: number;
            /** Avg Score */
            avg_score: number;
            /** Pass Rate */
            pass_rate: number;
        };
        /** EvalResultCreate */
        EvalResultCreate: {
            /** Trace Id */
            trace_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Eval Id */
            eval_id: string;
            /**
             * Eval Version
             * @default 1.0.0
             */
            eval_version: string;
            /** Verdict */
            verdict: string;
            /** Score */
            score: number;
            /** Reasoning */
            reasoning?: string | null;
            /** Judge Model */
            judge_model?: string | null;
            /** Evaluated At */
            evaluated_at?: string | null;
            /** Agent Id */
            agent_id?: string | null;
        };
        /** EvalResultOut */
        EvalResultOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Trace Id */
            trace_id: string;
            /** Span Id */
            span_id: string | null;
            /** Eval Id */
            eval_id: string;
            /** Eval Version */
            eval_version: string;
            /** Verdict */
            verdict: string;
            /** Score */
            score: number;
            /** Reasoning */
            reasoning: string | null;
            /** Judge Model */
            judge_model: string | null;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /** Agent Id */
            agent_id: string | null;
        };
        /** EvalUpdate */
        EvalUpdate: {
            /** Criterion Description */
            criterion_description?: string | null;
            evaluator_type?: components["schemas"]["EvaluatorType"] | null;
            /** Judge Config */
            judge_config?: Record<string, never> | null;
            /** Prompt Template */
            prompt_template?: string | null;
            /** Output Schema */
            output_schema?: Record<string, never> | null;
            /** Retrieval Config */
            retrieval_config?: Record<string, never> | null;
            /** Agreement Threshold */
            agreement_threshold?: number | null;
            /** Execution Modes */
            execution_modes?: Record<string, never> | null;
            /** Owner Team */
            owner_team?: string | null;
            /** Owner Email */
            owner_email?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * EvaluatorType
         * @enum {string}
         */
        EvaluatorType: "llm_as_judge" | "deterministic" | "embedding" | "hybrid";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RegressionAlertCreate */
        RegressionAlertCreate: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Eval Id */
            eval_id: string;
            /** Baseline Score */
            baseline_score: number;
            /** Current Score */
            current_score: number;
            /** Delta */
            delta: number;
            /** Candidate Causes */
            candidate_causes?: Record<string, never>[];
        };
        /** RegressionAlertOut */
        RegressionAlertOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Eval Id */
            eval_id: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Baseline Score */
            baseline_score: number;
            /** Current Score */
            current_score: number;
            /** Delta */
            delta: number;
            /** Candidate Causes */
            candidate_causes: Record<string, never>[];
            /** Status */
            status: string;
        };
        /** RegressionAlertUpdate */
        RegressionAlertUpdate: {
            status: components["schemas"]["RegressionStatus"];
        };
        /**
         * RegressionStatus
         * @enum {string}
         */
        RegressionStatus: "open" | "investigating" | "resolved" | "dismissed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_agents_get: {
        parameters: {
            query?: {
                criticality?: string | null;
                framework?: string | null;
                business_unit?: string | null;
                is_third_party?: boolean | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_agent_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evals_evals_get: {
        parameters: {
            query?: {
                status?: string | null;
                owner_team?: string | null;
                evaluator_type?: string | null;
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_eval_evals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_evals__eval_pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_eval_evals__eval_pk__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_for_review_evals__eval_pk__submit_for_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_evals__eval_pk__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deprecate_evals__eval_pk__deprecate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_calibration_evals__eval_pk__calibration_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachCalibrationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mappings_eval_agent_mapping_get: {
        parameters: {
            query?: {
                agent_id?: string | null;
                eval_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalAgentMappingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mapping_eval_agent_mapping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalAgentMappingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalAgentMappingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calibration_sets_calibration_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationSetOut"][];
                };
            };
        };
    };
    create_calibration_set_calibration_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationSetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calibration_set_calibration_sets__cal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_change_events_change_events_get: {
        parameters: {
            query?: {
                event_type?: string | null;
                agent_id?: string | null;
                actor?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_change_event_change_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_eval_results_eval_results_get: {
        parameters: {
            query?: {
                trace_id?: string | null;
                agent_id?: string | null;
                eval_id?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_eval_result_eval_results_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aggregate_eval_results_eval_results_aggregate_get: {
        parameters: {
            query?: {
                agent_id?: string | null;
                eval_id?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalResultAggregate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_regression_alerts_get: {
        parameters: {
            query?: {
                status?: string | null;
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegressionAlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_regression_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegressionAlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegressionAlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_regression_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegressionAlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_regression_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegressionAlertUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegressionAlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_audit_log_audit_log_get: {
        parameters: {
            query?: {
                entity_type?: string | null;
                entity_id?: string | null;
                action?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
