/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run-eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Eval
         * @description Offline mode: run one eval synchronously over a list of traces (FR-EO-4).
         */
        post: operations["run_eval_run_eval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample-once": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sample Once
         * @description Trigger a single sampled-online pass on demand (used by the demo + tests).
         */
        post: operations["sample_once_sample_once_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score
         * @description Run the agent's full approved+mapped suite on one trace and consolidate.
         */
        post: operations["score_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detect-regressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Regressions
         * @description Trigger a single regression-detection pass on demand (FR-RD; demo + tests).
         */
        post: operations["detect_regressions_detect_regressions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inline-eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inline Eval
         * @description Inline (synchronous gateway-gating) mode — scaffolded only (FR-EO-4).
         */
        post: operations["inline_eval_inline_eval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConsolidatedScore */
        ConsolidatedScore: {
            /** Status */
            status: string;
            /** Mean Score */
            mean_score: number;
            /** Threshold */
            threshold: number;
            /** Pass Count */
            pass_count: number;
            /** Fail Count */
            fail_count: number;
            /** Blocking Failures */
            blocking_failures: string[];
            /** Reasons */
            reasons: string[];
        };
        /** EvalVerdict */
        EvalVerdict: {
            /** Trace Id */
            trace_id: string;
            /** Span Id */
            span_id: string | null;
            /** Eval Id */
            eval_id: string;
            /** Eval Version */
            eval_version: string;
            /** Verdict */
            verdict: string;
            /** Score */
            score: number;
            /** Reasoning */
            reasoning: string;
            /** Judge Model */
            judge_model: string;
            /** Passed */
            passed: boolean;
            /** Error */
            error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RunEvalRequest */
        RunEvalRequest: {
            /** Eval Id */
            eval_id: string;
            /** Version */
            version?: string | null;
            /** Traces */
            traces?: components["schemas"]["TraceRef"][];
            /** Judge Model */
            judge_model?: string | null;
        };
        /** RunEvalResponse */
        RunEvalResponse: {
            /** Eval Id */
            eval_id: string;
            /** Eval Version */
            eval_version: string;
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["EvalVerdict"][];
        };
        /** SampleRunResponse */
        SampleRunResponse: {
            /** Sampled */
            sampled: number;
            /** Evaluated */
            evaluated: number;
            /** Results */
            results?: components["schemas"]["EvalVerdict"][];
        };
        /** ScoreRequest */
        ScoreRequest: {
            /** Agent */
            agent: string;
            trace: components["schemas"]["TraceRef"];
            /** Eval Ids */
            eval_ids?: string[] | null;
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Agent Id */
            agent_id: string | null;
            /** Agent Name */
            agent_name: string | null;
            /** Trace Id */
            trace_id: string;
            /** Results */
            results: components["schemas"]["EvalVerdict"][];
            consolidated: components["schemas"]["ConsolidatedScore"];
        };
        /**
         * TraceRef
         * @description A trace (and optionally span) to evaluate.
         *
         *     `input`/`output` may be supplied inline (the demo does this for determinism).
         *     When omitted, the orchestrator fetches them from Phoenix.
         */
        TraceRef: {
            /** Trace Id */
            trace_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Input */
            input?: string | null;
            /** Output */
            output?: string | null;
            /** Agent Id */
            agent_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    run_eval_run_eval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunEvalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_once_sample_once_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleRunResponse"];
                };
            };
        };
    };
    score_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_regressions_detect_regressions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    inline_eval_inline_eval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
